// Bóveda Kulttia — dataset curado y verificado (2026-07-10)
// 116 repos open-source verificados vivos vía GitHub API.
// Curaduría y descripciones: Kulttia Lab. Inspirado en la bóveda comunitaria de tododeia.com.
const BOVEDA_RESOURCES = [
 {
  "repo": "obra/superpowers",
  "name": "superpowers",
  "owner": "obra",
  "url": "https://github.com/obra/superpowers",
  "level": "intermedio",
  "cat": "skills",
  "desc": "Framework de skills agénticas y metodología de desarrollo completa. El estándar de facto para armar agentes que trabajan como equipo.",
  "stars": 250913,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "affaan-m/ECC",
  "name": "ECC",
  "owner": "affaan-m",
  "url": "https://github.com/affaan-m/ECC",
  "level": "avanzado",
  "cat": "agentes",
  "desc": "Sistema de optimización del harness: skills, instintos, memoria y seguridad para exprimir al máximo cualquier agente de código.",
  "stars": 227892,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "NousResearch/hermes-agent",
  "name": "hermes-agent",
  "owner": "NousResearch",
  "url": "https://github.com/NousResearch/hermes-agent",
  "level": "intermedio",
  "cat": "agentes",
  "desc": "Agente open-source que crece contigo: aprende de tus sesiones y se adapta a tu forma de trabajar.",
  "stars": 212238,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "multica-ai/andrej-karpathy-skills",
  "name": "andrej-karpathy-skills",
  "owner": "multica-ai",
  "url": "https://github.com/multica-ai/andrej-karpathy-skills",
  "level": "avanzado",
  "cat": "skills",
  "desc": "Un solo CLAUDE.md destilado de las observaciones de Karpathy sobre programar con LLMs. Menos ruido, mejor código.",
  "stars": 190092,
  "lang": null,
  "license": null
 },
 {
  "repo": "ollama/ollama",
  "name": "ollama",
  "owner": "ollama",
  "url": "https://github.com/ollama/ollama",
  "level": "avanzado",
  "cat": "herramientas",
  "desc": "Corre modelos open-source (DeepSeek, Qwen, Gemma y más) en tu propia máquina. La puerta de entrada a la IA local.",
  "stars": 175836,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "microsoft/markitdown",
  "name": "markitdown",
  "owner": "microsoft",
  "url": "https://github.com/microsoft/markitdown",
  "level": "principiante",
  "cat": "herramientas",
  "desc": "Convierte Word, Excel, PDF y casi cualquier documento a Markdown listo para LLMs. De Microsoft.",
  "stars": 164386,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "mattpocock/skills",
  "name": "skills",
  "owner": "mattpocock",
  "url": "https://github.com/mattpocock/skills",
  "level": "intermedio",
  "cat": "skills",
  "desc": "Las skills que Matt Pocock usa en su propio directorio .claude. Ingeniería real, sin humo.",
  "stars": 163103,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "anthropics/skills",
  "name": "skills",
  "owner": "anthropics",
  "url": "https://github.com/anthropics/skills",
  "level": "principiante",
  "cat": "skills",
  "desc": "El repositorio oficial de Agent Skills de Anthropic. Si vas a empezar por un solo repo, que sea este.",
  "stars": 159836,
  "lang": null,
  "license": null
 },
 {
  "repo": "langchain-ai/langchain",
  "name": "langchain",
  "owner": "langchain-ai",
  "url": "https://github.com/langchain-ai/langchain",
  "level": "avanzado",
  "cat": "agentes",
  "desc": "La plataforma de ingeniería de agentes más usada del ecosistema Python.",
  "stars": 141412,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "anthropics/claude-code",
  "name": "claude-code",
  "owner": "anthropics",
  "url": "https://github.com/anthropics/claude-code",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "El agente de código que vive en tu terminal, entiende tu codebase y ejecuta. La herramienta central de esta bóveda.",
  "stars": 137085,
  "lang": null,
  "license": null
 },
 {
  "repo": "msitarzewski/agency-agents",
  "name": "agency-agents",
  "owner": "msitarzewski",
  "url": "https://github.com/msitarzewski/agency-agents",
  "level": "intermedio",
  "cat": "agentes",
  "desc": "Una agencia completa de agentes IA: frontend, contenido, comunidad y más. Plug and play.",
  "stars": 129778,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "garrytan/gstack",
  "name": "gstack",
  "owner": "garrytan",
  "url": "https://github.com/garrytan/gstack",
  "level": "intermedio",
  "cat": "agentes",
  "desc": "El setup exacto de Claude Code de Garry Tan (Y Combinator): 23 herramientas que actúan como CEO, diseñador y eng manager.",
  "stars": 120816,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "github/spec-kit",
  "name": "spec-kit",
  "owner": "github",
  "url": "https://github.com/github/spec-kit",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "Toolkit oficial de GitHub para desarrollo guiado por especificaciones (Spec-Driven Development).",
  "stars": 119114,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Shubhamsaboo/awesome-llm-apps",
  "name": "awesome-llm-apps",
  "owner": "Shubhamsaboo",
  "url": "https://github.com/Shubhamsaboo/awesome-llm-apps",
  "level": "avanzado",
  "cat": "aprende",
  "desc": "Más de 100 apps de agentes y RAG que puedes clonar, personalizar y desplegar hoy.",
  "stars": 117100,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "google-gemini/gemini-cli",
  "name": "gemini-cli",
  "owner": "google-gemini",
  "url": "https://github.com/google-gemini/gemini-cli",
  "level": "avanzado",
  "cat": "herramientas",
  "desc": "El agente de terminal de Google. Útil para comparar flujos frente a Claude Code.",
  "stars": 105873,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "nextlevelbuilder/ui-ux-pro-max-skill",
  "name": "ui-ux-pro-max-skill",
  "owner": "nextlevelbuilder",
  "url": "https://github.com/nextlevelbuilder/ui-ux-pro-max-skill",
  "level": "intermedio",
  "cat": "creatividad",
  "desc": "Inteligencia de diseño UI/UX para tu agente: estilos, paletas, tipografías y stacks listos para usar.",
  "stars": 103528,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "VoltAgent/awesome-design-md",
  "name": "awesome-design-md",
  "owner": "VoltAgent",
  "url": "https://github.com/VoltAgent/awesome-design-md",
  "level": "intermedio",
  "cat": "creatividad",
  "desc": "Colección de archivos DESIGN.md de sistemas de diseño famosos. Suelta uno en tu proyecto y tu agente diseña con criterio.",
  "stars": 99780,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "openai/codex",
  "name": "codex",
  "owner": "openai",
  "url": "https://github.com/openai/codex",
  "level": "principiante",
  "cat": "herramientas",
  "desc": "El agente de código de OpenAI para terminal. El contrapunto natural de Claude Code.",
  "stars": 96689,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "JuliusBrussee/caveman",
  "name": "caveman",
  "owner": "JuliusBrussee",
  "url": "https://github.com/JuliusBrussee/caveman",
  "level": "intermedio",
  "cat": "skills",
  "desc": "Skill que recorta ~65% de tokens haciendo que el agente hable como cavernícola. Ahorro real, misma sustancia técnica.",
  "stars": 87314,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "thedotmack/claude-mem",
  "name": "claude-mem",
  "owner": "thedotmack",
  "url": "https://github.com/thedotmack/claude-mem",
  "level": "intermedio",
  "cat": "skills",
  "desc": "Memoria persistente entre sesiones: captura todo lo que hace tu agente y lo comprime en contexto útil.",
  "stars": 86627,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "Graphify-Labs/graphify",
  "name": "graphify",
  "owner": "Graphify-Labs",
  "url": "https://github.com/Graphify-Labs/graphify",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "Convierte cualquier carpeta de código en un grafo que tu agente entiende. Compatible con Claude Code, Codex y Cursor.",
  "stars": 81318,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "DietrichGebert/ponytail",
  "name": "ponytail",
  "owner": "DietrichGebert",
  "url": "https://github.com/DietrichGebert/ponytail",
  "level": "intermedio",
  "cat": "skills",
  "desc": "Hace que tu agente piense como el senior más perezoso de la sala: el mejor código es el que nunca se escribió.",
  "stars": 79252,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "nexu-io/open-design",
  "name": "open-design",
  "owner": "nexu-io",
  "url": "https://github.com/nexu-io/open-design",
  "level": "intermedio",
  "cat": "creatividad",
  "desc": "App de escritorio local-first y open-source para que tu agente de código sea también tu diseñador.",
  "stars": 76832,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "addyosmani/agent-skills",
  "name": "agent-skills",
  "owner": "addyosmani",
  "url": "https://github.com/addyosmani/agent-skills",
  "level": "intermedio",
  "cat": "skills",
  "desc": "Skills de ingeniería production-grade curadas por Addy Osmani (equipo de Google Chrome).",
  "stars": 75934,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "rtk-ai/rtk",
  "name": "rtk",
  "owner": "rtk-ai",
  "url": "https://github.com/rtk-ai/rtk",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "Proxy CLI que reduce 60-90% el consumo de tokens en comandos de desarrollo. Un binario en Rust, cero dependencias.",
  "stars": 69869,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "D4Vinci/Scrapling",
  "name": "Scrapling",
  "owner": "D4Vinci",
  "url": "https://github.com/D4Vinci/Scrapling",
  "level": "intermedio",
  "cat": "datos",
  "desc": "Framework de web scraping adaptativo: sirve igual para una petición suelta que para un crawl completo.",
  "stars": 68909,
  "lang": null,
  "license": "BSD-3-Clause"
 },
 {
  "repo": "ComposioHQ/awesome-claude-skills",
  "name": "awesome-claude-skills",
  "owner": "ComposioHQ",
  "url": "https://github.com/ComposioHQ/awesome-claude-skills",
  "level": "intermedio",
  "cat": "aprende",
  "desc": "Lista curada de skills, recursos y herramientas para personalizar tus flujos con Claude.",
  "stars": 67315,
  "lang": null,
  "license": null
 },
 {
  "repo": "shanraisshan/claude-code-best-practice",
  "name": "claude-code-best-practice",
  "owner": "shanraisshan",
  "url": "https://github.com/shanraisshan/claude-code-best-practice",
  "level": "principiante",
  "cat": "aprende",
  "desc": "De vibe coding a ingeniería agéntica: buenas prácticas ordenadas y accionables.",
  "stars": 62362,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Fission-AI/OpenSpec",
  "name": "OpenSpec",
  "owner": "Fission-AI",
  "url": "https://github.com/Fission-AI/OpenSpec",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "Desarrollo guiado por especificaciones (SDD) para asistentes de código IA.",
  "stars": 59610,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "upstash/context7",
  "name": "context7",
  "owner": "upstash",
  "url": "https://github.com/upstash/context7",
  "level": "intermedio",
  "cat": "mcp",
  "desc": "Documentación de código siempre actualizada para tus agentes. Se acabaron las APIs alucinadas.",
  "stars": 58835,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "crewAIInc/crewAI",
  "name": "crewAI",
  "owner": "crewAIInc",
  "url": "https://github.com/crewAIInc/crewAI",
  "level": "avanzado",
  "cat": "agentes",
  "desc": "Framework para orquestar agentes autónomos con roles que colaboran entre sí.",
  "stars": 55255,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "remotion-dev/remotion",
  "name": "remotion",
  "owner": "remotion-dev",
  "url": "https://github.com/remotion-dev/remotion",
  "level": "intermedio",
  "cat": "creatividad",
  "desc": "Crea videos programáticamente con React. La base sobre la que se construyen los editores IA.",
  "stars": 52688,
  "lang": null,
  "license": null
 },
 {
  "repo": "mvanhorn/last30days-skill",
  "name": "last30days-skill",
  "owner": "mvanhorn",
  "url": "https://github.com/mvanhorn/last30days-skill",
  "level": "intermedio",
  "cat": "skills",
  "desc": "Investiga cualquier tema en Reddit, X, YouTube y Hacker News de los últimos 30 días y te lo sintetiza.",
  "stars": 51223,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "run-llama/llama_index",
  "name": "llama_index",
  "owner": "run-llama",
  "url": "https://github.com/run-llama/llama_index",
  "level": "avanzado",
  "cat": "agentes",
  "desc": "La plataforma líder para agentes documentales y OCR sobre tus propios datos.",
  "stars": 50750,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "microsoft/VibeVoice",
  "name": "VibeVoice",
  "owner": "microsoft",
  "url": "https://github.com/microsoft/VibeVoice",
  "level": "principiante",
  "cat": "creatividad",
  "desc": "IA de voz open-source de frontera, desarrollada por Microsoft.",
  "stars": 50009,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "anthropics/claude-cookbooks",
  "name": "claude-cookbooks",
  "owner": "anthropics",
  "url": "https://github.com/anthropics/claude-cookbooks",
  "level": "avanzado",
  "cat": "aprende",
  "desc": "Los recetarios oficiales de Anthropic: notebooks con patrones probados para sacar más de Claude.",
  "stars": 47187,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "pbakaus/impeccable",
  "name": "impeccable",
  "owner": "pbakaus",
  "url": "https://github.com/pbakaus/impeccable",
  "level": "intermedio",
  "cat": "creatividad",
  "desc": "El lenguaje de diseño que vuelve a tu agente mejor diseñador. Directo al harness.",
  "stars": 45098,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "kepano/obsidian-skills",
  "name": "obsidian-skills",
  "owner": "kepano",
  "url": "https://github.com/kepano/obsidian-skills",
  "level": "intermedio",
  "cat": "skills",
  "desc": "Skills para que tu agente domine Obsidian: Markdown, Bases y JSON Canvas. Del CEO de Obsidian.",
  "stars": 40581,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "jamiepine/voicebox",
  "name": "voicebox",
  "owner": "jamiepine",
  "url": "https://github.com/jamiepine/voicebox",
  "level": "intermedio",
  "cat": "creatividad",
  "desc": "El estudio de voz IA open-source: clona, dicta, crea.",
  "stars": 40043,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "multica-ai/multica",
  "name": "multica",
  "owner": "multica-ai",
  "url": "https://github.com/multica-ai/multica",
  "level": "intermedio",
  "cat": "agentes",
  "desc": "Plataforma open-source de agentes gestionados: asigna tareas y da seguimiento como si fueran compañeros de equipo.",
  "stars": 39661,
  "lang": null,
  "license": null
 },
 {
  "repo": "vercel-labs/agent-browser",
  "name": "agent-browser",
  "owner": "vercel-labs",
  "url": "https://github.com/vercel-labs/agent-browser",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "CLI de automatización de navegador para agentes, por Vercel.",
  "stars": 38192,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "coreyhaines31/marketingskills",
  "name": "marketingskills",
  "owner": "coreyhaines31",
  "url": "https://github.com/coreyhaines31/marketingskills",
  "level": "intermedio",
  "cat": "negocio",
  "desc": "Skills de marketing para agentes: CRO, copywriting, SEO, analítica y growth engineering.",
  "stars": 37439,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "anthropics/prompt-eng-interactive-tutorial",
  "name": "prompt-eng-interactive-tutorial",
  "owner": "anthropics",
  "url": "https://github.com/anthropics/prompt-eng-interactive-tutorial",
  "level": "intermedio",
  "cat": "aprende",
  "desc": "El tutorial interactivo oficial de prompt engineering de Anthropic. Imprescindible para empezar en serio.",
  "stars": 36973,
  "lang": null,
  "license": null
 },
 {
  "repo": "microsoft/playwright-mcp",
  "name": "playwright-mcp",
  "owner": "microsoft",
  "url": "https://github.com/microsoft/playwright-mcp",
  "level": "principiante",
  "cat": "mcp",
  "desc": "Servidor MCP de Playwright: tu agente controla un navegador real.",
  "stars": 34895,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "heygen-com/hyperframes",
  "name": "hyperframes",
  "owner": "heygen-com",
  "url": "https://github.com/heygen-com/hyperframes",
  "level": "intermedio",
  "cat": "creatividad",
  "desc": "Escribe HTML, renderiza video. Pensado desde cero para agentes.",
  "stars": 34011,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "OpenBMB/VoxCPM",
  "name": "VoxCPM",
  "owner": "OpenBMB",
  "url": "https://github.com/OpenBMB/VoxCPM",
  "level": "intermedio",
  "cat": "creatividad",
  "desc": "Texto a voz multilingüe sin tokenizer: clonación de voz realista y open-source.",
  "stars": 32937,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "anthropics/claude-plugins-official",
  "name": "claude-plugins-official",
  "owner": "anthropics",
  "url": "https://github.com/anthropics/claude-plugins-official",
  "level": "principiante",
  "cat": "skills",
  "desc": "El directorio oficial de plugins de Claude Code, gestionado por Anthropic.",
  "stars": 31884,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "vercel-labs/agent-skills",
  "name": "agent-skills",
  "owner": "vercel-labs",
  "url": "https://github.com/vercel-labs/agent-skills",
  "level": "principiante",
  "cat": "skills",
  "desc": "La colección oficial de skills de agentes de Vercel.",
  "stars": 28886,
  "lang": null,
  "license": null
 },
 {
  "repo": "davila7/claude-code-templates",
  "name": "claude-code-templates",
  "owner": "davila7",
  "url": "https://github.com/davila7/claude-code-templates",
  "level": "principiante",
  "cat": "herramientas",
  "desc": "CLI para configurar y monitorear Claude Code con plantillas listas para producción.",
  "stars": 28550,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "blader/humanizer",
  "name": "humanizer",
  "owner": "blader",
  "url": "https://github.com/blader/humanizer",
  "level": "intermedio",
  "cat": "skills",
  "desc": "Elimina las marcas de texto generado por IA. Que tu escritura vuelva a sonar humana.",
  "stars": 28474,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "ScrapeGraphAI/Scrapegraph-ai",
  "name": "Scrapegraph-ai",
  "owner": "ScrapeGraphAI",
  "url": "https://github.com/ScrapeGraphAI/Scrapegraph-ai",
  "level": "intermedio",
  "cat": "datos",
  "desc": "Scraper en Python potenciado por IA: describe qué quieres extraer y el grafo hace el resto.",
  "stars": 28230,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "eyaltoledano/claude-task-master",
  "name": "claude-task-master",
  "owner": "eyaltoledano",
  "url": "https://github.com/eyaltoledano/claude-task-master",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "Sistema de gestión de tareas con IA que se integra en Cursor, Windsurf y compañía.",
  "stars": 27805,
  "lang": null,
  "license": null
 },
 {
  "repo": "BloopAI/vibe-kanban",
  "name": "vibe-kanban",
  "owner": "BloopAI",
  "url": "https://github.com/BloopAI/vibe-kanban",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "Kanban para orquestar varios agentes de código a la vez y multiplicar tu output.",
  "stars": 27320,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "JCodesMore/ai-website-cloner-template",
  "name": "ai-website-cloner-template",
  "owner": "JCodesMore",
  "url": "https://github.com/JCodesMore/ai-website-cloner-template",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "Replica la estructura de cualquier web con un comando usando agentes de código.",
  "stars": 27209,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "openai/codex-plugin-cc",
  "name": "codex-plugin-cc",
  "owner": "openai",
  "url": "https://github.com/openai/codex-plugin-cc",
  "level": "intermedio",
  "cat": "skills",
  "desc": "Usa Codex desde Claude Code para revisar código o delegar tareas. Dos cerebros, una terminal.",
  "stars": 27174,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "vercel-labs/skills",
  "name": "skills",
  "owner": "vercel-labs",
  "url": "https://github.com/vercel-labs/skills",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "npx skills: el gestor abierto para instalar skills en cualquier agente.",
  "stars": 25656,
  "lang": null,
  "license": null
 },
 {
  "repo": "ahujasid/blender-mcp",
  "name": "blender-mcp",
  "owner": "ahujasid",
  "url": "https://github.com/ahujasid/blender-mcp",
  "level": "avanzado",
  "cat": "mcp",
  "desc": "Controla Blender desde cualquier LLM. Modelado 3D conversacional.",
  "stars": 23657,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Anil-matcha/Open-Generative-AI",
  "name": "Open-Generative-AI",
  "owner": "Anil-matcha",
  "url": "https://github.com/Anil-matcha/Open-Generative-AI",
  "level": "avanzado",
  "cat": "creatividad",
  "desc": "Estudio gratuito de generación de imagen y video con más de 200 modelos. La alternativa abierta a las plataformas de pago.",
  "stars": 22949,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "coleam00/Archon",
  "name": "Archon",
  "owner": "coleam00",
  "url": "https://github.com/coleam00/Archon",
  "level": "intermedio",
  "cat": "agentes",
  "desc": "Constructor de harness open-source: vuelve el desarrollo con IA determinista y repetible.",
  "stars": 22819,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Donchitos/Claude-Code-Game-Studios",
  "name": "Claude-Code-Game-Studios",
  "owner": "Donchitos",
  "url": "https://github.com/Donchitos/Claude-Code-Game-Studios",
  "level": "avanzado",
  "cat": "agentes",
  "desc": "Convierte Claude Code en un estudio de videojuegos completo: 49 agentes y 72 workflows coordinados.",
  "stars": 22794,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "czlonkowski/n8n-mcp",
  "name": "n8n-mcp",
  "owner": "czlonkowski",
  "url": "https://github.com/czlonkowski/n8n-mcp",
  "level": "intermedio",
  "cat": "mcp",
  "desc": "MCP que construye workflows de n8n por ti, desde Claude Desktop, Claude Code o Cursor.",
  "stars": 22213,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "anthropics/courses",
  "name": "courses",
  "owner": "anthropics",
  "url": "https://github.com/anthropics/courses",
  "level": "intermedio",
  "cat": "aprende",
  "desc": "Los cursos educativos oficiales de Anthropic, en formato repositorio.",
  "stars": 22131,
  "lang": null,
  "license": null
 },
 {
  "repo": "alchaincyf/huashu-design",
  "name": "huashu-design",
  "owner": "alchaincyf",
  "url": "https://github.com/alchaincyf/huashu-design",
  "level": "principiante",
  "cat": "creatividad",
  "desc": "Skill de diseño HTML-nativo: prototipos de alta fidelidad, presentaciones y animaciones desde Claude Code.",
  "stars": 21164,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "mksglu/context-mode",
  "name": "context-mode",
  "owner": "mksglu",
  "url": "https://github.com/mksglu/context-mode",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "Optimiza la ventana de contexto: aísla el output de las herramientas (~98% de reducción) y persiste la memoria de sesión.",
  "stars": 18768,
  "lang": null,
  "license": null
 },
 {
  "repo": "teng-lin/notebooklm-py",
  "name": "notebooklm-py",
  "owner": "teng-lin",
  "url": "https://github.com/teng-lin/notebooklm-py",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "API no oficial de NotebookLM en Python, con skill agéntica para explotarlo desde código.",
  "stars": 17495,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "anthropics/claude-quickstarts",
  "name": "claude-quickstarts",
  "owner": "anthropics",
  "url": "https://github.com/anthropics/claude-quickstarts",
  "level": "intermedio",
  "cat": "aprende",
  "desc": "Proyectos oficiales para arrancar aplicaciones desplegables con Claude en minutos.",
  "stars": 17198,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "muratcankoylan/Agent-Skills-for-Context-Engineering",
  "name": "Agent-Skills-for-Context-Engineering",
  "owner": "muratcankoylan",
  "url": "https://github.com/muratcankoylan/Agent-Skills-for-Context-Engineering",
  "level": "intermedio",
  "cat": "aprende",
  "desc": "Skills de context engineering y arquitecturas multi-agente listas para producción.",
  "stars": 17043,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "browser-use/browser-harness",
  "name": "browser-harness",
  "owner": "browser-use",
  "url": "https://github.com/browser-use/browser-harness",
  "level": "avanzado",
  "cat": "agentes",
  "desc": "Harness de navegador auto-reparable: los LLMs completan cualquier tarea web.",
  "stars": 15855,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "yusufkaraaslan/Skill_Seekers",
  "name": "Skill_Seekers",
  "owner": "yusufkaraaslan",
  "url": "https://github.com/yusufkaraaslan/Skill_Seekers",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "Convierte sitios de documentación, repos y PDFs en skills de Claude, con detección de conflictos.",
  "stars": 14414,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "microsoft/playwright-cli",
  "name": "playwright-cli",
  "owner": "microsoft",
  "url": "https://github.com/microsoft/playwright-cli",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "CLI de Playwright: graba, genera código, inspecciona selectores y toma screenshots.",
  "stars": 11900,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "Vinzent03/obsidian-git",
  "name": "obsidian-git",
  "owner": "Vinzent03",
  "url": "https://github.com/Vinzent03/obsidian-git",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "Control de versiones Git dentro de Obsidian, con commit-and-sync automático.",
  "stars": 11507,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "rmyndharis/OpenWA",
  "name": "OpenWA",
  "owner": "rmyndharis",
  "url": "https://github.com/rmyndharis/OpenWA",
  "level": "avanzado",
  "cat": "herramientas",
  "desc": "Gateway de WhatsApp API gratuito, open-source y self-hosted.",
  "stars": 10958,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "AgriciDaniel/claude-seo",
  "name": "claude-seo",
  "owner": "AgriciDaniel",
  "url": "https://github.com/AgriciDaniel/claude-seo",
  "level": "intermedio",
  "cat": "negocio",
  "desc": "Skill universal de SEO: 25 sub-skills y 18 sub-agentes que cubren SEO técnico, E-E-A-T, schema y GEO.",
  "stars": 10897,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "nidhinjs/prompt-master",
  "name": "prompt-master",
  "owner": "nidhinjs",
  "url": "https://github.com/nidhinjs/prompt-master",
  "level": "principiante",
  "cat": "skills",
  "desc": "Skill que escribe el prompt exacto para cualquier herramienta de IA. Cero tokens desperdiciados.",
  "stars": 10358,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "virgiliojr94/book-to-skill",
  "name": "book-to-skill",
  "owner": "virgiliojr94",
  "url": "https://github.com/virgiliojr94/book-to-skill",
  "level": "intermedio",
  "cat": "skills",
  "desc": "Convierte cualquier libro técnico en PDF en una skill de Claude Code, lista para estudiar y consultar mientras trabajas.",
  "stars": 8350,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "YouMind-OpenLab/awesome-gpt-image-2",
  "name": "awesome-gpt-image-2",
  "owner": "YouMind-OpenLab",
  "url": "https://github.com/YouMind-OpenLab/awesome-gpt-image-2",
  "level": "principiante",
  "cat": "creatividad",
  "desc": "Biblioteca masiva de prompts de generación de imagen con previews, actualizada a diario.",
  "stars": 8128,
  "lang": null,
  "license": null
 },
 {
  "repo": "emilkowalski/skills",
  "name": "skills",
  "owner": "emilkowalski",
  "url": "https://github.com/emilkowalski/skills",
  "level": "principiante",
  "cat": "creatividad",
  "desc": "Skills para design engineers, por Emil Kowalski. Animación e interacción con estándar alto.",
  "stars": 7069,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "ChrisWiles/claude-code-showcase",
  "name": "claude-code-showcase",
  "owner": "ChrisWiles",
  "url": "https://github.com/ChrisWiles/claude-code-showcase",
  "level": "intermedio",
  "cat": "aprende",
  "desc": "Ejemplo completo de configuración de Claude Code: hooks, skills, agentes, comandos y GitHub Actions.",
  "stars": 5985,
  "lang": null,
  "license": null
 },
 {
  "repo": "nolly-studio/cult-ui",
  "name": "cult-ui",
  "owner": "nolly-studio",
  "url": "https://github.com/nolly-studio/cult-ui",
  "level": "intermedio",
  "cat": "creatividad",
  "desc": "Componentes para design engineers: Tailwind, compatibles con shadcn y fáciles de extender.",
  "stars": 5805,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "dlt-hub/dlt",
  "name": "dlt",
  "owner": "dlt-hub",
  "url": "https://github.com/dlt-hub/dlt",
  "level": "avanzado",
  "cat": "datos",
  "desc": "Librería Python open-source que vuelve trivial cargar datos desde cualquier fuente hacia cualquier destino.",
  "stars": 5584,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "FlorianBruniaux/claude-code-ultimate-guide",
  "name": "claude-code-ultimate-guide",
  "owner": "FlorianBruniaux",
  "url": "https://github.com/FlorianBruniaux/claude-code-ultimate-guide",
  "level": "intermedio",
  "cat": "aprende",
  "desc": "Guía exhaustiva de Claude Code: workflows agénticos, hooks, skills, servidores MCP y quizzes de práctica.",
  "stars": 5393,
  "lang": null,
  "license": "CC-BY-SA-4.0"
 },
 {
  "repo": "mixedbread-ai/mgrep",
  "name": "mgrep",
  "owner": "mixedbread-ai",
  "url": "https://github.com/mixedbread-ai/mgrep",
  "level": "avanzado",
  "cat": "herramientas",
  "desc": "Grep semántico para todo: código, imágenes, PDFs. Búsqueda por significado desde la CLI.",
  "stars": 4294,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "haris-musa/excel-mcp-server",
  "name": "excel-mcp-server",
  "owner": "haris-musa",
  "url": "https://github.com/haris-musa/excel-mcp-server",
  "level": "intermedio",
  "cat": "mcp",
  "desc": "Servidor MCP para manipular archivos Excel directamente desde tu agente.",
  "stars": 4005,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "anthropics/anthropic-sdk-python",
  "name": "anthropic-sdk-python",
  "owner": "anthropics",
  "url": "https://github.com/anthropics/anthropic-sdk-python",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "El SDK oficial de Anthropic para Python. La base de cualquier app sobre Claude.",
  "stars": 3725,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "crystaldba/postgres-mcp",
  "name": "postgres-mcp",
  "owner": "crystaldba",
  "url": "https://github.com/crystaldba/postgres-mcp",
  "level": "avanzado",
  "cat": "mcp",
  "desc": "Acceso configurable a Postgres y análisis de performance para ti y tus agentes.",
  "stars": 3030,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "supabase/mcp",
  "name": "mcp",
  "owner": "supabase",
  "url": "https://github.com/supabase/mcp",
  "level": "avanzado",
  "cat": "mcp",
  "desc": "Conecta Supabase con tus asistentes de IA. Base de datos conversacional.",
  "stars": 2795,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "snyk/agent-scan",
  "name": "agent-scan",
  "owner": "snyk",
  "url": "https://github.com/snyk/agent-scan",
  "level": "avanzado",
  "cat": "herramientas",
  "desc": "Escáner de seguridad para agentes, servidores MCP y skills. Desarrollado por Snyk.",
  "stars": 2763,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "anthropics/anthropic-sdk-typescript",
  "name": "anthropic-sdk-typescript",
  "owner": "anthropics",
  "url": "https://github.com/anthropics/anthropic-sdk-typescript",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "El SDK oficial de Anthropic para TypeScript.",
  "stars": 2036,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "apify/apify-mcp-server",
  "name": "apify-mcp-server",
  "owner": "apify",
  "url": "https://github.com/apify/apify-mcp-server",
  "level": "intermedio",
  "cat": "mcp",
  "desc": "Tus agentes extraen datos de redes sociales, buscadores, mapas y e-commerce vía MCP.",
  "stars": 1774,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "severity1/claude-code-prompt-improver",
  "name": "claude-code-prompt-improver",
  "owner": "severity1",
  "url": "https://github.com/severity1/claude-code-prompt-improver",
  "level": "intermedio",
  "cat": "skills",
  "desc": "Hook que mejora tus prompts al vuelo: escribe vibras, obtén precisión.",
  "stars": 1654,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "BayramAnnakov/claude-reflect",
  "name": "claude-reflect",
  "owner": "BayramAnnakov",
  "url": "https://github.com/BayramAnnakov/claude-reflect",
  "level": "intermedio",
  "cat": "skills",
  "desc": "Sistema de auto-aprendizaje: captura tus correcciones y preferencias, y las sincroniza entre sesiones.",
  "stars": 1237,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "affaan-m/agentshield",
  "name": "agentshield",
  "owner": "affaan-m",
  "url": "https://github.com/affaan-m/agentshield",
  "level": "avanzado",
  "cat": "herramientas",
  "desc": "Detecta vulnerabilidades en configuraciones de agentes, servidores MCP y permisos de herramientas.",
  "stars": 961,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "jordanrendric/claude-video-vision",
  "name": "claude-video-vision",
  "owner": "jordanrendric",
  "url": "https://github.com/jordanrendric/claude-video-vision",
  "level": "intermedio",
  "cat": "skills",
  "desc": "Dale ojos a Claude: extrae frames y entiende videos desde Claude Code.",
  "stars": 957,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "davideast/stitch-mcp",
  "name": "stitch-mcp",
  "owner": "davideast",
  "url": "https://github.com/davideast/stitch-mcp",
  "level": "intermedio",
  "cat": "mcp",
  "desc": "Lleva diseños de UI generados en Google Stitch directo a tu flujo de desarrollo.",
  "stars": 929,
  "lang": null,
  "license": "Apache-2.0"
 },
 {
  "repo": "browser-use/bux",
  "name": "bux",
  "owner": "browser-use",
  "url": "https://github.com/browser-use/bux",
  "level": "avanzado",
  "cat": "agentes",
  "desc": "Agente 24/7 de automatización de navegador estilo Playwright, con Browser Use Cloud.",
  "stars": 402,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "zhongweili/nanobanana-mcp-server",
  "name": "nanobanana-mcp-server",
  "owner": "zhongweili",
  "url": "https://github.com/zhongweili/nanobanana-mcp-server",
  "level": "intermedio",
  "cat": "mcp",
  "desc": "Generación de imágenes vía Gemini con selección inteligente de modelo y salida en 4K.",
  "stars": 374,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/whatsapp-agentkit",
  "name": "whatsapp-agentkit",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/whatsapp-agentkit",
  "level": "intermedio",
  "cat": "agentes",
  "desc": "Monta tu propio agente de WhatsApp con IA en menos de 30 minutos, sin saber programar. En español.",
  "stars": 344,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/the-architect",
  "name": "the-architect",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/the-architect",
  "level": "intermedio",
  "cat": "agentes",
  "desc": "Meta-agente que diseña blueprints completos de software: describe qué quieres y te entrega el plano.",
  "stars": 330,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/editor-pro-max",
  "name": "editor-pro-max",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/editor-pro-max",
  "level": "intermedio",
  "cat": "creatividad",
  "desc": "Editor de video con IA construido sobre Remotion: describe el video en lenguaje natural y se edita solo.",
  "stars": 205,
  "lang": null,
  "license": null
 },
 {
  "repo": "Hainrixz/claude-webkit",
  "name": "claude-webkit",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/claude-webkit",
  "level": "intermedio",
  "cat": "creatividad",
  "desc": "Construye una página web profesional en minutos, sin saber programar. En español.",
  "stars": 173,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/cyber-neo",
  "name": "cyber-neo",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/cyber-neo",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "Agente de ciberseguridad open-source: escanea tu proyecto contra el OWASP Top 10.",
  "stars": 167,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/maia-skill",
  "name": "maia-skill",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/maia-skill",
  "level": "intermedio",
  "cat": "negocio",
  "desc": "5 agentes analizan cripto, acciones, forex y commodities en paralelo, adaptados a tu perfil de riesgo. Para estudiar mercados, no para apostar.",
  "stars": 118,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/claude-banana",
  "name": "claude-banana",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/claude-banana",
  "level": "intermedio",
  "cat": "creatividad",
  "desc": "Convierte ideas sueltas en prompts de imagen precisos: fórmula de 7 componentes y más de 70 estilos creativos.",
  "stars": 82,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/humanizalo",
  "name": "humanizalo",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/humanizalo",
  "level": "principiante",
  "cat": "skills",
  "desc": "Detecta 40 patrones de escritura IA y reescribe el texto para que suene humano. Bilingüe y con auto-auditoría.",
  "stars": 78,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/auto-crm",
  "name": "auto-crm",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/auto-crm",
  "level": "intermedio",
  "cat": "negocio",
  "desc": "CRM local con IA que se personaliza a tu negocio. 100% local, open-source.",
  "stars": 58,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/skill-vault",
  "name": "skill-vault",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/skill-vault",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "Tu biblioteca personal de skills: organiza, analiza y busca, con análisis de seguridad incluido.",
  "stars": 54,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/claude-ads",
  "name": "claude-ads",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/claude-ads",
  "level": "avanzado",
  "cat": "negocio",
  "desc": "Auditoría y optimización de pauta multi-plataforma que se auto-actualiza: Google, Meta, TikTok.",
  "stars": 51,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/all-deploy",
  "name": "all-deploy",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/all-deploy",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "Despliega cualquier web, API o agente a internet, con auditoría estricta antes de cada deploy.",
  "stars": 38,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/claude-seo-ai",
  "name": "claude-seo-ai",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/claude-seo-ai",
  "level": "intermedio",
  "cat": "negocio",
  "desc": "Toolkit de SEO + búsqueda IA (GEO/AEO): auditoría con dos scores y fixer opcional.",
  "stars": 27,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/abogado-del-diablo",
  "name": "abogado-del-diablo",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/abogado-del-diablo",
  "level": "intermedio",
  "cat": "skills",
  "desc": "Pon a Claude en tu contra: crítica dura de tu idea, plan o código antes de que lo haga el mercado.",
  "stars": 27,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/agente-pagokit",
  "name": "agente-pagokit",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/agente-pagokit",
  "level": "avanzado",
  "cat": "negocio",
  "desc": "Analiza tu proyecto, hace 3 preguntas y genera la integración de pagos completa.",
  "stars": 22,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/claude-db",
  "name": "claude-db",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/claude-db",
  "level": "intermedio",
  "cat": "datos",
  "desc": "El experto en bases de datos multi-paradigma: diseña esquemas y audítalos con dos scores independientes.",
  "stars": 18,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/aprende-skill",
  "name": "aprende-skill",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/aprende-skill",
  "level": "principiante",
  "cat": "skills",
  "desc": "Tu agente aprende de sus errores: /aprende revisa la sesión y guarda las lecciones para la próxima.",
  "stars": 13,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/enpoint-agentkit",
  "name": "enpoint-agentkit",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/enpoint-agentkit",
  "level": "intermedio",
  "cat": "herramientas",
  "desc": "Abre endpoints REST de solo lectura en tu app sin ser experto: detecta tu stack y lo arma por ti.",
  "stars": 1,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/claude-cmd",
  "name": "claude-cmd",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/claude-cmd",
  "level": "principiante",
  "cat": "herramientas",
  "desc": "Instala Claude Code en 1 clic en Mac y Windows, con ícono directo en tu escritorio.",
  "stars": 0,
  "lang": null,
  "license": "MIT"
 },
 {
  "repo": "Hainrixz/claude-skill",
  "name": "claude-skill",
  "owner": "Hainrixz",
  "url": "https://github.com/Hainrixz/claude-skill",
  "level": "principiante",
  "cat": "skills",
  "desc": "Pregunta qué puede hacer Claude y dónde: un router de capacidades entre Chat, Code y Cowork.",
  "stars": 0,
  "lang": null,
  "license": "Apache-2.0"
 }
];
